/**
 * Kaleidoscope category and vendor for every concrete Datadog profile.
 *
 * The registry assigns one category per enterprise (all of Cisco is
 * `switch`), which is wrong for an ASA or an access point, so each Datadog
 * profile is classified here by hand. The converter refuses a concrete
 * profile that has no row, so a new upstream profile forces a decision.
 *
 * `vendor` is set only where the registry has no row for the enterprise or its
 * vendor name does not fit the product.
 *
 * Judgement calls, reviewable in one place:
 *  - Routers, SD-WAN edges, load balancers, WAN optimizers, packet brokers,
 *    PDUs, environmental sensors, KVM/console servers: `generic` (the format
 *    has no router/pdu/sensor category).
 *  - Wireless LAN controllers: `access_point`.
 *  - Storage arrays and backup appliances: `nas`.
 *  - Network appliances that are really servers (ISE, ICM, BlueCat, UCS): `server`.
 */
export type Category = 'ups' | 'switch' | 'access_point' | 'server' | 'printer' | 'firewall' | 'nas' | 'generic';

export const PROFILE_CLASS: Record<string, { category: Category; vendor?: string | null }> = {
  '3com': { category: 'switch', vendor: '3Com' },
  '3com-huawei': { category: 'switch', vendor: '3Com' },
  'a10-thunder': { category: 'generic', vendor: 'A10 Networks' },
  'alcatel-lucent-ent': { category: 'switch' },
  'alcatel-lucent-ind': { category: 'switch' },
  'alcatel-lucent-omni-access-wlc': { category: 'access_point' },
  'anue': { category: 'generic', vendor: 'Anue Systems' },
  'apc': { category: 'ups' },
  'apc-netbotz': { category: 'generic' },
  'apc-pdu': { category: 'generic' },
  'apc_ups': { category: 'ups' },
  'arista': { category: 'switch' },
  'arista-switch': { category: 'switch' },
  'aruba': { category: 'switch' },
  'aruba-access-point': { category: 'access_point' },
  'aruba-clearpass': { category: 'server' },
  'aruba-cx-switch': { category: 'switch', vendor: 'Aruba' },
  'aruba-mobility-controller': { category: 'access_point' },
  'aruba-switch': { category: 'switch' },
  'aruba-wireless-controller': { category: 'access_point' },
  'audiocodes-mediant-sbc': { category: 'generic' },
  'avaya-aura-media-server': { category: 'server', vendor: 'Avaya' },
  'avaya-cajun-switch': { category: 'switch', vendor: 'Avaya' },
  'avaya-media-gateway': { category: 'generic', vendor: 'Avaya' },
  'avaya-nortel-ethernet-routing-switch': { category: 'switch' },
  'avocent-acs': { category: 'generic' },
  'avtech': { category: 'generic' },
  'avtech-roomalert-32s': { category: 'generic' },
  'avtech-roomalert-3e': { category: 'generic' },
  'avtech-roomalert-3s': { category: 'generic' },
  'barracuda-cloudgen': { category: 'firewall', vendor: 'Barracuda' },
  'bluecat-server': { category: 'server', vendor: 'BlueCat' },
  'brocade-fc-switch': { category: 'switch' },
  'brother-net-printer': { category: 'printer' },
  'chatsworth_pdu': { category: 'generic' },
  'checkpoint': { category: 'firewall' },
  'chrysalis-luna-hsm': { category: 'generic', vendor: 'SafeNet' },
  'cisco': { category: 'switch' },
  'cisco-3850': { category: 'switch' },
  'cisco-access-point': { category: 'access_point' },
  'cisco-asa': { category: 'firewall' },
  'cisco-asa-5525': { category: 'firewall' },
  'cisco-asr': { category: 'generic' },
  'cisco-catalyst': { category: 'switch' },
  'cisco-catalyst-wlc': { category: 'access_point' },
  'cisco-csr1000v': { category: 'generic' },
  'cisco-firepower': { category: 'firewall' },
  'cisco-firepower-asa': { category: 'firewall' },
  'cisco-ironport-email': { category: 'generic', vendor: 'Cisco' },
  'cisco-ise': { category: 'server' },
  'cisco-isr': { category: 'generic' },
  'cisco-legacy-wlc': { category: 'access_point' },
  'cisco-load-balancer': { category: 'generic' },
  'cisco-nexus': { category: 'switch' },
  'cisco-sb': { category: 'switch' },
  'cisco-ucs': { category: 'server' },
  'cisco-wan-optimizer': { category: 'generic' },
  'cisco_icm': { category: 'server' },
  'cisco_isr_4431': { category: 'generic' },
  'cisco_uc_virtual_machine': { category: 'server' },
  'citrix-netscaler': { category: 'generic' },
  'citrix-netscaler-sdx': { category: 'generic' },
  'cradlepoint': { category: 'generic' },
  'cyberpower-pdu': { category: 'generic' },
  'dell': { category: 'server' },
  'dell-emc-data-domain': { category: 'nas' },
  'dell-force10': { category: 'switch' },
  'dell-os10': { category: 'switch' },
  'dell-powerconnect': { category: 'switch' },
  'dell-poweredge': { category: 'server' },
  'dell-sonicwall': { category: 'firewall' },
  'dialogic-media-gateway': { category: 'generic', vendor: 'Dialogic' },
  'dlink-dgs-switch': { category: 'switch' },
  'eaton-epdu': { category: 'generic' },
  'exagrid': { category: 'nas', vendor: 'ExaGrid' },
  'extreme-switching': { category: 'switch' },
  'f5-big-ip': { category: 'generic' },
  'fireeye': { category: 'generic' },
  'fortinet': { category: 'firewall' },
  'fortinet-appliance': { category: 'firewall' },
  'fortinet-fortigate': { category: 'firewall' },
  'fortinet-fortiswitch': { category: 'switch' },
  'generic-device': { category: 'generic', vendor: null },
  'generic-ups': { category: 'ups', vendor: null },
  'gigamon': { category: 'generic' },
  'hp-h3c-switch': { category: 'switch' },
  'hp-icf-switch': { category: 'switch' },
  'hp-ilo': { category: 'server' },
  'hp-ilo4': { category: 'server' },
  'hpe-bladesystem-enclosure': { category: 'server' },
  'hpe-msa': { category: 'nas' },
  'hpe-nimble': { category: 'nas', vendor: 'HPE' },
  'hpe-proliant': { category: 'server' },
  'huawei': { category: 'switch' },
  'huawei-access-controllers': { category: 'access_point' },
  'huawei-routers': { category: 'generic' },
  'huawei-switches': { category: 'switch' },
  'ibm-datapower-gateway': { category: 'generic', vendor: 'IBM' },
  'ibm-lenovo-server': { category: 'server' },
  'idrac': { category: 'server' },
  'infinera-coriant-groove': { category: 'generic', vendor: 'Infinera' },
  'infoblox-ipam': { category: 'server' },
  'isilon': { category: 'nas' },
  'ixsystems-truenas': { category: 'nas' },
  'juniper': { category: 'switch' },
  'juniper-ex': { category: 'switch' },
  'juniper-mx': { category: 'generic' },
  'juniper-pulse-secure': { category: 'firewall' },
  'juniper-qfx': { category: 'switch' },
  'juniper-srx': { category: 'firewall' },
  'kyocera-printer': { category: 'printer' },
  'linksys': { category: 'switch' },
  'mcafee-web-gateway': { category: 'firewall', vendor: 'McAfee' },
  'meraki': { category: 'generic' },
  'meraki-cloud-controller': { category: 'generic' },
  'mikrotik-router': { category: 'generic' },
  'nasuni-filer': { category: 'nas', vendor: 'Nasuni' },
  'nec-univerge': { category: 'generic', vendor: 'NEC' },
  'netapp': { category: 'nas' },
  'netgear': { category: 'switch' },
  'netgear-access-point': { category: 'access_point' },
  'netgear-readynas': { category: 'nas' },
  'netgear-switch': { category: 'switch' },
  'netscout-switch': { category: 'generic', vendor: 'NetScout' },
  'nvidia-cumulus-linux-switch': { category: 'switch' },
  'nvidia-mellanox-switchx': { category: 'switch' },
  'omron-cj-ethernet-ip': { category: 'generic', vendor: 'Omron' },
  'opengear-console-manager': { category: 'generic' },
  'opengear-infrastructure-manager': { category: 'generic' },
  'palo-alto': { category: 'firewall' },
  'palo-alto-cloudgenix': { category: 'generic', vendor: 'Palo Alto' },
  'peplink': { category: 'generic' },
  'pf-sense': { category: 'firewall', vendor: 'Netgate' },
  'raritan-dominion': { category: 'generic' },
  'riverbed': { category: 'generic' },
  'riverbed-interceptor': { category: 'generic' },
  'riverbed-steelhead': { category: 'generic' },
  'ruckus': { category: 'access_point' },
  'ruckus-unleashed': { category: 'access_point' },
  'ruckus-wap': { category: 'access_point' },
  'server-iron-switch': { category: 'generic' },
  'servertech': { category: 'generic' },
  'servertech-pdu3': { category: 'generic' },
  'servertech-pdu4': { category: 'generic' },
  'silverpeak-edgeconnect': { category: 'generic' },
  'sinetica-eagle-i': { category: 'generic', vendor: 'Sinetica' },
  'sophos-xgs-firewall': { category: 'firewall' },
  'synology-disk-station': { category: 'nas' },
  'tp-link': { category: 'switch' },
  'tripplite': { category: 'ups' },
  'tripplite-pdu': { category: 'generic' },
  'tripplite-ups': { category: 'ups' },
  'ubiquiti-unifi': { category: 'access_point' },
  'ubiquiti-unifi-security-gateway': { category: 'firewall' },
  'velocloud-edge': { category: 'generic', vendor: 'VMware' },
  'vertiv-liebert-ac': { category: 'generic' },
  'vertiv-watchdog': { category: 'generic' },
  'vmware-esx': { category: 'server' },
  'watchguard': { category: 'firewall' },
  'western-digital-mycloud-ex2-ultra': { category: 'nas', vendor: 'Western Digital' },
  'zebra-printer': { category: 'printer' },
  'zyxel-switch': { category: 'switch' },
};
